version: '3'
volumes:
  node-modules:
  mysql_data:

networks:
  golang_network:
    external: true

services:
  server:
    build: ./services/server
    volumes:
       - "./services/server/src/:/usr/src/"
    working_dir: /usr/src
    tty: true
    ports: 
      - 8080:8080
    env_file:
      - ./services/db/.env
    depends_on:
      - db
    networks:
      - golang_network
    container_name: server
  db:
    build: ./services/db
    tty: true
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./services/db/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/db/init:/docker-entrypoint-initdb.d
    networks:
      - golang_network
    container_name: db
  client:
    build: ./services/client
    volumes:
       - "./services/client/app/:/usr/app/"
       - node-modules:/usr/app/node_modules
    working_dir: /usr/app
    tty: true
    ports: 
      - 3000:3000
    container_name: client
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./services/swagger-ui/swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/swagger.yaml
    ports:
      - "8081:8080"
    networks:
      - golang_network
    container_name: swagger-ui
