version: '3'
services:
  server:
    build: ./services/server
    volumes:
       - "./services/server/src/:/usr/src/"
    working_dir: /usr/src
    tty: true
    ports: 
      - 8080:8080
  client:
    build: ./services/client
    volumes:
       - "./services/client/app/:/usr/app/"
       - node-modules:/usr/app/node_modules
    working_dir: /usr/app
    tty: true
    ports: 
      - 3000:3000

volumes:
  node-modules: