version: '3'
volumes:
  node-modules:
  mysql_data:

services:
  server:
    build: ./services/server
    volumes:
       - "./services/server/src/:/usr/local/src/"
    working_dir: /usr/local/src
    tty: true
    env_file:
      - ./services/db/.env
    depends_on:
      - db
    container_name: server
    environment:
      - "GOPATH=/usr/local/go"
  db:
    build: ./services/db
    tty: true
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./services/db/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/db/init:/docker-entrypoint-initdb.d
    container_name: db
  client:
    build: ./services/client
    volumes:
       - "./services/client/app/:/usr/local/app/"
       - node-modules:/usr/local/app/node_modules
    working_dir: /usr/local/app
    tty: true
    ports: 
      - 3000:3000
    container_name: client
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./services/swagger-ui/swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/swagger.yaml
    ports:
      - "8081:8080"
    container_name: swagger-ui
