name: back-ci
on: pull_request
jobs:
  lint-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: services/server/src
