name: back-cd
on:
  pull_request
  # # テスト用で一旦コメントアウト
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: start building
        run: go build main.go
        working-directory: ./services/server/src
      - name: deketa?
        run: ls -l services/server/src
      - name: archive build file
        uses: actions/upload-artifact@v3
        with:
          name: nabelog-server-build-main-file
          path: services/server/src/main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download build file
        uses: actions/download-artifact@v3
        with:
          name: nabelog-server-build-main-file
      - name: setup secretKey
        env:
          PRIVATE_KEY: ${{ secrets.SK }}
          HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${HOST} >> ~/.ssh/known_hosts
      - name: scp for back server
        env:
          USER_NAME: ${{ secrets.SSH_USERNAME }}
          HOST: ${{ secrets.SSH_HOST }}
        run: scp -i ~/.ssh/id_rsa main ${USER_NAME}@${HOST}:/usr/local/src/
      - name: deketa?
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SK }}
          port: ${{ secrets.SSH_PORT }}
          script: ls -l /usr/local/src/
